name: Linux Build & Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]

    name: Checking
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
